### PR TITLE
Comparison without operator overload failure

### PR DESCRIPTION
**Pull request by calvinchengx**
Using .get() allows us to compare the raw value of memory address underlying each, which would then make the comparison valid

Fixes https://github.com/openwebf/webf/issues/351

### CODE REVIEW

**Comment by andycall** [comment]
TKS for your PR.

But this compile error seems strange because the CI on Windows is working. However, if this pull request also passes our CI, I would like to approve it

https://github.com/openwebf/webf/actions/runs/5056627689/jobs/9074322726

**Comment by andycall** [comment]
image
The unit test was failed

**Comment by calvinchengx** [comment]
@andycall - where do I get or build the `webf_unit_test.exe` binary? Without there, I have to depend on the CI CD builds to know if the unit test passes.

On my macOS, `webf_unit_test` binary is built, but on windows, my `webf_unit_test.exe` does not get built. And so I can't run the unit tests on windows.

**Comment by andycall** [comment]
```
node scripts/run_bridge_unit_test.js
```

**Comment by calvinchengx** [comment]
Seems like everything passes except 

integration_test_f33 (FlexBoxLayoutAndPositionedLayout)

Reference: https://github.com/openwebf/webf/actions/runs/5069996148/jobs/9105040069

Any idea if this is related to my operator overload change?

**Comment by andycall** [comment]
Due to the unstable Github macOS runners (the integration_test_f37 running on our self-hosted runner never fails), some specs may need to be re-run.

**Review by andycall — APPROVED** [review]

**Pull request merged**
