### PR TITLE
feat: Support background-clip text

### PR DESCRIPTION
**Pull request by devjiangzhou**
RT

### CODE REVIEW

**Review by andycall — APPROVED** [review]

**Comment by devjiangzhou** [comment]
> 

 I added 2 new test specs, and it seems that this issue did not occur.

**Comment by devjiangzhou** [comment]
> Rendering is not correct when the `background-clip` changes. For example `empty => 'text'` and `'text' => empty`. Needs to fix.


I added 2 new test specs, and it seems that this issue did not occur.

**Comment by XGHeaven** [comment]
@devjiangzhou You can view it by pasting the following code to `bundle.js`.
```js
const p = document.createElement('p')
p.style.background ='linear-gradient(60deg, red, yellow, red, yellow, red)'
p.style.color = 'rgba(0, 0, 0, 0.5)'

p.appendChild(document.createTextNode('1 The background is clipped to the foreground text.'))

document.body.appendChild(p)

setTimeout(() => {
    p.style.backgroundClip = 'text'
}, 1000)
```
image

If change background-clip from `'text'` to `''`.
```js
// others is same
p.style.backgroundClip = 'text'

setTimeout(() => {
    p.style.backgroundClip = ''
}, 1000)
```
image

**Comment by devjiangzhou** [comment]
> @devjiangzhou You can view it by pasting the following code to `bundle.js`.
> 
> ```js
> const p = document.createElement('p')
> p.style.background ='linear-gradient(60deg, red, yellow, red, yellow, red)'
> p.style.color = 'rgba(0, 0, 0, 0.5)'
> 
> p.appendChild(document.createTextNode('1 The background is clipped to the foreground text.'))
> 
> document.body.appendChild(p)
> 
> setTimeout(() => {
>     p.style.backgroundClip = 'text'
> }, 1000)
> ```
> 
> image
> 
> If change background-clip from `'text'` to `''`.
> 
> ```js
> // others is same
> p.style.backgroundClip = 'text'
> 
> setTimeout(() => {
>     p.style.backgroundClip = ''
> }, 1000)
> ```
> 
> image

fixed

**Review by XGHeaven — APPROVED** [review]

**Pull request merged**
