### PR TITLE
feat: enable BIGNUM

### PR DESCRIPTION
**Pull request by neeboo**
Enable BIGNUM support, related https://github.com/openwebf/webf/issues/12

modify CMakeLists.txt, adding CONFIG_BIGNUM and libbf.c
adding missing headers and types in bindings/qjs/qjs_engine_patch.h
modify dependencies in polyfill
modify assets.js to show it works
TODO:  awaits webf_websocket upgrade or build it ourselves

### CODE REVIEW

**Comment by neeboo** [comment]
> @neeboo Looks like the test are failed.

It seems that the latest commit of [openwebf:refactor/remove_host_class](https://github.com/openwebf/webf/tree/refactor/remove_host_class) failed. 

I will try starting with a clean commit

**Comment by andycall** [comment]
@neeboo I guess the main reason of test failed is the prebuilt binary in linux machine of qjsc are old version's built.

**Comment by neeboo** [comment]
> @neeboo I thought the main reason of test failed is the prebuilt binary in linux machine of qjsc are old version's built.

ahh , ok, will solve that too

**Comment by neeboo** [comment]
> @neeboo I thought the main reason of test failed is the prebuilt binary in linux machine of qjsc are old version's built.

The problem exist in websocket plugin which is not compiled using latest qjsc.
Would you see this pr and see if you can move it to another branch maybe allowing build?

https://github.com/openwebf/plugins/pull/1

**Comment by AlexV525** [comment]
@andycall Any blockers with this PR and https://github.com/openwebf/plugins/pull/1 ?

**Comment by andycall** [comment]
@AlexV525 The BigInt feature support for QuickJS will break the bytecode format with current WebF versions. So it needs time to change the implementation of the BigInt support in QuickJS to make it backward compatible with the original bytecode format.

**Comment by AlexV525** [comment]
> So it needs time to change the implementation of the BigInt support in QuickJS to make it backward compatible with the original bytecode format.

Where is the time? Do we have a roadmap or a TODO list to indicate what is missing? Any status indication about what should be updated to help users create patches for contributions?

**Comment by andycall** [comment]
> e is the time? Do we have a roadmap or a TODO list to indicate what is missing? Any status indication about what should be updated to help users create patches for contributions?

**Comment by bai-3** [comment]
@andycall Are there any plans to restart this PR? This feature is very important for web3 applications.

**Comment by andycall** [comment]
@bai-3 https://github.com/openwebf/webf/pull/440

**Pull request closed without merging**
